# Numpy notes

In [1]:
import numpy as np

#### Create an array

In [2]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

[[1 2 3]
 [4 5 6]]


### It takes less memory

In [7]:
import sys

s = range(1000)
print('Normal range:',sys.getsizeof(5) * len(s))
d = np.arange(1000)
print('Numpy range:',d.size * d.itemsize)

Normal range: 28000
Numpy range: 4000


### It's faster

In [9]:
import time
l1, l2 = range(1000000), range(1000000)
a1, a2 = np.arange(1000000), np.arange(1000000)

start = time.time()
result = [(x, y) for x, y in zip(l1, l2)]
print('Normal range:',(time.time() - start) * 1000)

start = time.time()
result = a1 + a2
print('Numpy range:',(time.time() - start) * 1000)

Normal range: 188.51041793823242
Numpy range: 48.375606536865234


### Dim/Shape/size/Reshape

In [14]:
a = np.array([[1, 2, 3], ['a', 32, 3]])
print(a.ndim)  # 2
print(a.itemsize)  # 44
print(a.dtype)  # <U11
print(a.size)  # 6
print(a.shape)  # (2,3)
print(a.reshape(1, -1))  # [['1' '2' '3' 'a' '32' '3']]

2
44
<U11
6
(2, 3)
[['1' '2' '3' 'a' '32' '3']]


### Slicing

In [16]:
a = np.array([[1, 2, 3, 4, 5],
              ['a', 'b', 'c', 'd', 'e'],
              [11, 22, 33, 44, 55],
              ['A', ' B', 'C', 'D', 'E'],
              [6, 7, 8, 9, 0],
              ['aa', 'bb', 'cc', 'dd', 'ee']])
print(a[1:3, 2:4])

[['c' 'd']
 ['33' '44']]


### Linspace/Max/Min

In [18]:
a = np.linspace(0, 10, 6)
print(a)
print(a.max())
print(a.sum())

[ 0.  2.  4.  6.  8. 10.]
10.0
30.0


### Sum on axis/sqrt

In [20]:
a = np.array([(1, 2, 3, 4, 5),
              (11, 22, 33, 44, 55),
              (6, 7, 8, 9, 0)])

print(a.sum(axis=0))
print(a.sum(axis=1))
print(np.sqrt(a))
print(np.std(a))

[18 31 44 57 60]
[ 15 165  30]
[[1.         1.41421356 1.73205081 2.         2.23606798]
 [3.31662479 4.69041576 5.74456265 6.63324958 7.41619849]
 [2.44948974 2.64575131 2.82842712 3.         0.        ]]
16.32993161855452


### Stacking

In [35]:
a = np.array([(4, 4, 4),
              (3, 2, 1)])
b = np.array([(2, 2, 3),
              (3, 2, 1)])
print(a - b, '\n')
print(np.vstack((a, b)), '\n')
print()
print(np.hstack((a, b)))

[[2 2 1]
 [0 0 0]] 

[[4 4 4]
 [3 2 1]
 [2 2 3]
 [3 2 1]] 


[[4 4 4 2 2 3]
 [3 2 1 3 2 1]]


### Sin/Cos/Ravel

In [36]:
a = np.array([(4, 4, 4),
              (3, 2, 1)])
print(a.ravel(), '\n')
print(np.sin(a), '\n')
print(np.cos(a))

[4 4 4 3 2 1] 

[[-0.7568025  -0.7568025  -0.7568025 ]
 [ 0.14112001  0.90929743  0.84147098]] 

[[-0.65364362 -0.65364362 -0.65364362]
 [-0.9899925  -0.41614684  0.54030231]]


### Exp/Log

In [37]:
ar = np.array([1, 2, 3])
print(np.exp(ar), '\n')
print(np.log10(ar))

[ 2.71828183  7.3890561  20.08553692] 

[0.         0.30103    0.47712125]


### Filtering

In [45]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr[arr % 2 == 1], '\n')
arr[arr % 2 == 1] = -1
print(arr, '\n')
a = np.arange(10)
b = np.where(a % 2 == 0, -1, a)
print(b, '\n')
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
b = np.reshape(arr, (2, -1))
print(b)

[1 3 5 7 9] 

[-1  2 -1  4 -1  6 -1  8 -1] 

[-1  1 -1  3 -1  5 -1  7 -1  9] 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


### Stacking

In [47]:
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)
c = np.vstack([a, b])  # hstack
c = np.concatenate([a, b], axis=1)  # axis=0
c = np.r_[a, b]  # c_[a, b]
print(a, '\n')
print(b, '\n')
print(c

[[0 1 2 3 4]
 [5 6 7 8 9]] 

[[1 1 1 1 1]
 [1 1 1 1 1]] 

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


### Repeat/Tile

In [54]:
a = np.array([1, 2, 3])
print(a)
print(np.repeat(a, 3))
print(np.tile(a, 3))

[1 2 3]
[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


### Difference/Intersection

In [66]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([4, 5, 6, 4])
print(a, '\n')
print(b, '\n')
print(np.intersect1d(a, b), '\n')
print(np.setdiff1d(a, b), '\n')
index = np.where((a >= 2) & (a <= 4))
print(a[index], '\n')
print(a[(a >= 2) & (a <= 4)])# [ 6  9 10]

[1 2 3 4 5] 

[4 5 6 4] 

[4 5] 

[1 2 3] 

[2 3 4] 

[2 3 4]


### Vectorize

In [70]:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([1, 1, 1, 1, 1, 1, 1])

def my_func(x, y):
    return x * 10 + y

pair_max = np.vectorize(my_func)
print(pair_max(a, b))

[51 71 91 81 61 41 51]


### Reversing

In [78]:
a = np.arange(1, 10).reshape((3,3))
print(a[:,[1,0,2]], '\n')
print(a[[1,0,2], :], '\n')
print(a[::-1], '\n')
print(a[:, ::-1], '\n')
print(a[::-1, ::-1])

[[2 1 3]
 [5 4 6]
 [8 7 9]] 

[[4 5 6]
 [1 2 3]
 [7 8 9]] 

[[7 8 9]
 [4 5 6]
 [1 2 3]] 

[[3 2 1]
 [6 5 4]
 [9 8 7]] 

[[9 8 7]
 [6 5 4]
 [3 2 1]]
